### ISSUE TITLE
fmcw board problem 

### ISSUE THREAD

**Issue by mjk1376** [Ttl/fmcw3#11]
hello, i have order your board from osh and buy it's component and solder them but i have problem. vivado can not determine fpga. i change eeprom ic and program it with my own hex file and when i attach cable the computer show device attachment in device manager but vivado in auto-connect mode it did not know the board. all the voltages are correct. board after attaching to 12 v consume 0.19 A and after i attach type-b cable it show 0.21 A. can you give me hint about the problem. 
thanks

**Comment by Ttl** [comment]
Vivado is not supported. You need to use openocd. See `openocd` folder.
