### ISSUE TITLE
Bill of Materials Challenges

### ISSUE THREAD

**Issue by zack-emmert** [Ttl/fmcw3#3]
Once again attempting to track down all of the components involved, a large number of entries lack the information necessary to locate them. The majority of entries lack a Manufacturer Part Number, making it very difficult to track down the components. Examples include the 15dB Coupler, and "C_0402b 10n." I have precisely no clue what the second component actually is, and there is significant ambiguity locating the first one. Clarification regarding the MPNs of many of the components would be very helpful.

**Comment by Ttl** [comment]
"15 dB Coupler" is the coupler on PA output made of PCB traces, there is nothing to populate.

"C_0402b" is 0402 capacitor footprint. 10n is the value.

I know it could be clearer, but I don't have the time or motivation to fill the manufacturer part numbers. Both of these should have been clear if you would have looked them up in the schematic.
