### ISSUE TITLE
Design Rule Check (DRC) problems of fmcw3

### ISSUE THREAD

**Issue by bigbenbell** [Ttl/fmcw3#9]
Dear Henrik,

You really contributed a beautiful fmcw radar design. We are trying to build our own radar system using the design of fmcw3. When outputting Gerber files, there were a large number of errors during running DRC. For example:
1 Error: Annular width (board setup constraints...n annular width 0.1000 mm; actual 0.0000 mm)
2 Error: Clearance violation (netclass 'Default' clearance 0.1300 mm; actual 0.0000 mm)
3 Error: Hole clearance violation...
4 Error: Courtyards overlap...
5 Error: Drill out of range...

**I'm not sure if this will affect the homemade radar.**

![figure](https://github.com/Ttl/fmcw3/assets/30232436/ce157420-3eac-4a92-908b-9027078f1d3a)

**Comment by Ttl** [comment]
The layout has been made with now quite old Kicad version. There might be some incompatibilities when opening with newer version. The files are provided as is.

Note that some components are now obsolete (At least PA). Make sure to find replacements or some old stock for them.
